# Generated by Django 2.1.15 on 2020-06-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like_movie',
        ),
    ]
