# Generated by Django 2.1.15 on 2020-06-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_comment_uesrname'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='uesrname',
            field=models.TextField(default='이름없음'),
        ),
    ]
