# Generated by Django 2.1.15 on 2020-06-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_article_uesrname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='uesrname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='uesrname',
            field=models.TextField(),
        ),
    ]
