# Generated by Django 2.1.15 on 2020-06-15 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_auto_20200616_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRateMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='movieuser',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movieuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='MovieUser',
        ),
        migrations.AddField(
            model_name='movie',
            name='rate',
            field=models.ManyToManyField(through='movies.UserRateMovie', to=settings.AUTH_USER_MODEL),
        ),
    ]
