# Generated by Django 2.1.15 on 2020-06-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200616_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rate_value',
            field=models.IntegerField(default=0),
        ),
    ]
