# Generated by Django 2.1.15 on 2020-06-16 04:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_rate_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='like',
            field=models.ManyToManyField(default=0, related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
