# Generated by Django 2.1.15 on 2020-06-16 04:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20200616_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='like',
            field=models.ManyToManyField(null=True, related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
