# Generated by Django 2.1.15 on 2020-06-16 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20200616_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.ManyToManyField(related_name='rate_user', through='movies.UserRateMovie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userratemovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_movie', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='userratemovie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
